[package]
name = "cli"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "simplicity-unchained"
path = "src/main.rs"

[dependencies]
anyhow = "1.0"
clap = { workspace = true }
core = { path = "../core" }
hal-simplicity = { workspace = true }
hex = { workspace = true }
reqwest = { version = "0.11", features = ["blocking", "json"] }
serde = { workspace = true }
serde_json = { workspace = true }
